Add contact me section
PedroH-Neves/My-first-portfolio pull request #3
Opened 2022-08-24 19:41 UTC by PedroH-Neves

- Finished the contact me section
- Add all requirements for contact section
- Add more css styles

2022-08-24 20:07 UTC, phelian23 requested changes
Hi @Team, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Great job setting up the correct linters ✔️
Professional documentation ✔️
Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 20:07 UTC, phelian23 commented on index.html
>          <button class="submit-btn primary-color button-hover button-pressed" type="button">Get in touch</button>
- [x] Kindly make use of `type=" submit"` for this button, as it is used to submit the form

2022-08-24 20:07 UTC, phelian23 commented on style.css
>  }
- [ ] Kindly ensure that your design matches the Figma template as much as possible. Please take a look at the width of the form fields.
Your design
![Capture](https://user-images.githubusercontent.com/85095702/186512541-1e3fe8c7-3fb8-40f3-b8e0-1f7c51bf84af.PNG)
Figma template
![figma](https://user-images.githubusercontent.com/85095702/186512602-49d84931-54f5-4862-8d1d-6e5f35a64ccd.PNG)

- [ ] Also kindly align the text above the form input to the center

2022-08-24 21:19 UTC, ichala requested changes
Hi @PedroH-Neves , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Correct workflow ✅ 
-  Form submission and validation are perfect ✅ 

 ## Required Changes ♻️

- [ ] **_Check the comments below_**

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 21:19 UTC, ichala commented on index.html
>        </form>
- [ ] as the previous reviewer requested kindly fix the margins and the alignments to match Figma design

![image](https://user-images.githubusercontent.com/89282221/186525348-0cb1cbc3-8fe1-4515-a04e-54eefd1f1d32.png)

2022-08-25 19:36 UTC, ichala approved these changes
Hi @PedroH-Neves  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Correct Workflow ✔️
- Changes Implemented ✔️

 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
*************************************
# Optional Suggestions 

- N/A



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 19:40 UTC, merged