desktop version
PedroH-Neves/My-first-portfolio pull request #5
Opened 2022-08-26 22:36 UTC by PedroH-Neves

- Add all desktop content 
- Use of CSS media queries
- Add new assets for desktop sizes
- Make nav menu functional

2022-08-26 23:13 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @PedroH-Neves 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Please check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 23:13 UTC, ha-manel commented on index.html
> +      </ul>
- [x] Kindly add the missing icon.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/187000871-0887c895-61b4-40b9-92e9-4e391b6536e2.png)

## Figma:
![image](https://user-images.githubusercontent.com/50721479/187000890-889e2a14-5b85-4f64-8a38-98bcf8f9a4fb.png)

2022-08-26 23:13 UTC, ha-manel commented on index.html
> +        </div>
- [ ] Kindly edit this section's size to make it match the Figma design 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/187001010-50830cc2-603b-4b29-883c-046b749490c9.png)

## Figma:
![image](https://user-images.githubusercontent.com/50721479/187001002-13357c39-95df-40a7-ad11-53701f87cbbd.png)

2022-08-26 23:13 UTC, ha-manel commented on index.html
> +      <section id="portfolio" class="projects-section-two">
- [ ] Kindly edit the desktop version of the cards to make it match Figma; when the project is hovered on with the mouse the description and the dark opacity disappear and a `See Project` button appears at the bottom of the image and takes the whole image width. 

## Default state:
![image](https://user-images.githubusercontent.com/50721479/186996458-b47772b5-31bf-4047-8695-c4eebe400d85.png)

## On hover:
![image](https://user-images.githubusercontent.com/50721479/186996487-bd4e5016-58f2-4182-a7d0-4afcbd32baae.png)

2022-08-26 23:13 UTC, ha-manel commented on index.html
>          <p class="about-text primary-color">Hello I’m a software developer! I can help you build a product , feature or
- [ ] Kindly edit the font for this section, as well as the `see project` button for the cards, the `skills`, and the `form`.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/187001407-5ef06442-2acf-49f5-a5e8-6695060f03df.png)
![image](https://user-images.githubusercontent.com/50721479/187001392-c55c57f5-b627-4d6c-a173-1f0eabb06b66.png)
![image](https://user-images.githubusercontent.com/50721479/187001423-f1163c43-f1e1-4d32-8207-f6d512da874a.png)
![image](https://user-images.githubusercontent.com/50721479/187001429-5e3de15c-d4cf-4234-ba80-3f116bdc3d28.png)

## Figma:
![image](https://user-images.githubusercontent.com/50721479/187001460-ab927561-2d8b-4d38-a7b9-e1fb87f123e8.png)
![image](https://user-images.githubusercontent.com/50721479/187001474-0cf60476-1d9b-4245-9d9c-d2197c9851e7.png)
![image](https://user-images.githubusercontent.com/50721479/187001481-183c19ec-ff12-4253-b5f0-f07a4241f494.png)
![image](https://user-images.githubusercontent.com/50721479/187001494-5e2e7e9b-c375-46fb-bbf8-97d293a64259.png)

2022-08-26 23:13 UTC, ha-manel commented on style.css
> +    grid-template-rows: 1fr 1fr 1fr;
- [ ] Kindly fix this error, there are 2 rows in the grid but you made 3 which caused the section to have a huge empty gap at the bottom, you can remove the row and add `margin-bottom` instead 💯 

![image](https://user-images.githubusercontent.com/50721479/187001671-2dde1624-2ce8-4f11-b6b3-26424b9fbfa0.png)

2022-08-26 23:13 UTC, ha-manel commented on style.css
> +  }
- [ ] Kindly fix the issues in mobile version 👍 

![image](https://user-images.githubusercontent.com/50721479/187001767-fdd5f09c-94f1-42a0-bc4e-d2831abab26a.png)

2022-08-27 23:14 UTC, codecaiine approved these changes
Hi @PedroH-Neves , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights


- Good requested changes application :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Great design :heavy_check_mark: 

## Optional suggestions
- [ ] [OPTIONAL] I would like to recommend you work on your mobile version and your desktop version navbar contact icon position cause it is important to follow Figma design as much as possible :+1:  
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 23:16 UTC, merged